version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chrome-python-app
    ports:
      - "8000:8000"
    environment:
      - CHROME_BIN=/usr/bin/google-chrome
      - CHROME_DRIVER=/usr/local/bin/chromedriver
    volumes:
      - .:/app
    restart: unless-stopped
